//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 10:31:56 PM UYT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://clienteFinalSOAP/empresas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package clientefinalsoap.empresas;
