spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/enriquecamejo/configuraciones.git
          search-paths:
              - "{application}"
          default-label: master
